### ISSUE TITLE
Remove tokenless support for Codecov

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#1001]
When tokenless support was added in Cake.Recipe we were using the Codecov-exe project, which at that time could do tokenless uploads of the reports, once everything was moved over to the official Codecov CLI project tokenless uploads could be done as well.

At some point, tokenless support was removed, and while the CLI will attempt to upload the report to the server this will in almost every case not be accepted by the server. As such, since this is known to fail quite ofter, their own documentation has removed any references of tokenless uploads, we should update Cake.Recipe to require a token to be specified to upload coverage reports. This is similar to how Coveralls support is implemented.

**Comment by nils-a** [comment]
@AdmiringWorm I have the feeling that tokenless should still be supported for PR runs on GitHub. While that feature is currently broken, I fell we should keep in mind that this is supposed to work.

**Comment by AdmiringWorm** [comment]
@nils-a I honestly debated that myself whether it should or not. But I feel it may not be appropriate when 90% of runs will hit the rate limit (When updating Cake.Codecov, I have every single PR hit the rate limit except 1).

I don't think the authors even consider it to be broken, as they even mentions the rate limit in their documentation: https://docs.codecov.com/docs/codecov-uploader#supporting-token-less-uploads-for-forks-of-open-source-repos-using-codecov

**Comment by AdmiringWorm** [comment]
I am all ears to hearing different opinions on this matter though, and I don't mind changing the PR I opened to instead of requiring a token, to perhaps not make successful Codecov run a requirement instead.

**Comment by pascalberger** [comment]
For my cases I stopped using it, when it stopped to work reliable. Therefore I would be OK to have it removed.

**Comment by pascalberger** [comment]
> Have you found an alternative? I've grown relatively fond of those "This PR drops the coverage by 10%" comments...

While I also appreciate the comments, when the build failed it was always when I tried to merge something, so I was lazy and just disabled it 😄

**Comment by AdmiringWorm** [comment]
From how I see it, there are two options available.

1. Only upload coverage reports to Codecov when a token is specified (This is what my PR currently do).
2. When uploading coverage reports to Codecov and a token is missing, always return a zero exit code even on failures (but only do this on GitHub action), and use non-zero exit code on failures only when a token is available.

**Comment by nils-a** [comment]
I like the PR the way it is now. :+1:
