### ISSUE TITLE
Document Publishing issue when there are no changes to commit

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#104]
@gep13 commented on [Wed May 31 2017](https://github.com/cake-contrib/Cake.Wyam.Recipe/issues/5)

When documentation hasn't changed between releases, an error is thrown when trying to make a commit for no changes, resulting in a failed build.

**Comment by gep13** [comment]
This occurred here:

https://ci.appveyor.com/project/cakecontrib/cake-wyam-recipe/build/0.2.0.build.17

**Comment by gep13** [comment]
@devlead any thoughts on why this might be happening?

I thought I was handling this situation here:

https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/wyam.cake#L146

Thanks!

**Comment by pascalberger** [comment]
@gep13 We found out that LibGit2Sharp, and subsequently GitHasUncommitedChanges, has issues with returning state if file name casing has changed. Can this be your issue?

**Comment by gep13** [comment]
@pascalberger hmmm, honestly not sure.  Any ideas on how to check that?

**Comment by pascalberger** [comment]
@gep13 We added some code to our internal build script for printing out modified files (we have a check that build fails if files are modified):

```
using (var repo = new Repository(repositoryRootFolder.FullPath))
{
    foreach (var fileEntry in repo.RetrieveStatus())
    {
        var state = fileEntry.State;
        if (state == FileStatus.Ignored)
        {
            continue;
        }

        if (state == FileStatus.Unaltered)
        {
            continue;
        }

        context.Warning("  {0}: {1}", fileEntry.FilePath, fileEntry.State);
    }
}
```

All cases which we could reproduce there were some changes in file name casing involved in a previous commit.

@devlead I could craeate a PR if there is interested for the above functionality in Cake.Git?

**Comment by devlead** [comment]
v0.15.0 just released is has a new `GitHasStagedChanges` alias, @gep13 could you add that check before commit so see if it returns false? That would mean add didn't stage any changes.

**Comment by gep13** [comment]
@devlead oh, interesting, that could be exactly what I need.  Will give that a try, thanks! 👍

**Comment by devlead** [comment]
@pascalberger as an extra check in GitHasUncommitedChanges?  I.e. if repo is dirty then also do your check?

**Comment by pascalberger** [comment]
@devlead Thought more about a separate alias `PrintModifiedFiles` or `GetModifiedFiles`. But could also add it to `GetHasUncommitedChanges` and throw an exception there if an inconsistent state was detected.

**Comment by andreasnilsen** [comment]
@gep13  Could you check https://github.com/cake-contrib/Cake.Recipe/issues/147#issuecomment-419477541 ? I think bbc2368 introduced it because of a potential bug in the underlying Cake.Git method used.

**Comment by gep13** [comment]
I haven't seen an issue with this lately, and as such, I am going to call this fixed for now.  If there are still issues, we can investigate later.
