### ISSUE TITLE
Enable option to build source nuget packages

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#112]
With the latest changes I added in PR #111 this added a parameter that can be set to `true` to create source/symbol nuget packages.

I request to change the necessary line(s) to enable the creation of source packages when running the task `Create-Nuget-Package(s)`.

With this change, another change would also need to be added.
Since nuget (when pushing to nuget.org) by default also pushes similary named symbol packages to a SymbolSource server, there would be a need to ignore such package so they aren't pushed directly to nuget.org instead.

There is possibly a change needed when pushing to MyGet as well as I believe they have their own SymbolSource server with a different url.
But that is not something I'm completely certain of.

**Comment by gep13** [comment]
>@AdmiringWorm said...
There is possibly a change needed when pushing to MyGet as well as I believe they have their own SymbolSource server with a different url.
But that is not something I'm completely certain of.

Any chance that @xavierdecoster or @maartenba can chime in here with exactly what is required when pushing source package to MyGet?  Thanks!

**Comment by maartenba** [comment]
http://docs.myget.org/docs/reference/feed-endpoints

In other words: push symbols to `/F/<your-feed-name>/api/v2/package` and be happy ;-)

**Comment by AdmiringWorm** [comment]
Awesome, so no need for us to change anything for pushing to myget.

Thanks @maartenba

**Comment by gep13** [comment]
@maartenba thank you for confirming this! :+1:

**Comment by AdmiringWorm** [comment]
I will need to start looking into this, currently there is a problem when source package generation is enabled and packages are pushed to nuget.org. (package already exists error).

Of course, that only happens with .NET Core builds currently, but since the option exists it must be completed.

**Comment by gep13** [comment]
Looking at this, I think this would be related to the removal of GitLink.
