### ISSUE TITLE
Support for Transifex

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#127]
Would be nice to have support for the Transifex Cake Addin, to have full support of the transifex utility would be difficult though as it requires a hack to be runned on a build server (or without user interaction).

**Comment by gep13** [comment]
@AdmiringWorm what sort of hack is required?

**Comment by AdmiringWorm** [comment]
@gep13 

actually it depends, if the user doesn't have a `.tx` directory in the root of the repository, then no hack is acquired (only running 
`tx init --token $apiToken --host=www.transifex.com`
, or 
`tx init --user=userName --pass=password --host=www.transifex.com`,
and also needs to run `tx set` with the necessary arguments, and for each resource).
The support for `tx init` is scheduled to be supported in the addin on the next release, `tx set` isn't scheduled until the release after that though.

if the `.tx` directory already exists, and `tx init` have never been run on the user computed (like would be true when running on appveyor).
We'll need to create a `.transifexrc` in the `%USERPROFILE%` directory with a specific format.

Example using `appveyor.yml`, but could definitely be moved to a cake build script instead.
https://github.com/AdmiringWorm/Hello-Transifex/blob/master/.appveyor.yml#L10-L12`

**Comment by gep13** [comment]
@AdmiringWorm I would have no objection to any of this.

**Comment by AdmiringWorm** [comment]
Well, good news I guess. I've finally gotten around to start working on this one.

Don't know yet when I will complete it though.
I've updated the issue with which tasks and how I plan to implement them (well somewhat at least).

**Comment by gep13** [comment]
@AdmiringWorm very cool!  I think that this will be a VERY useful addition to Cake.Recipe.  Thank you for taking the time to add this!

**Comment by AdmiringWorm** [comment]
@gep13 no problem, I should probably also consider adding some documentation on how to enable transifex when using Cake.Recipe.

But that won't be a priority right away.

**Comment by gep13** [comment]
Understood, we can add that later...  There are lots of things in Cake.Recipe that still need to be documented 😄

**Comment by AdmiringWorm** [comment]
I've opened a WIP PR, and move the list of tasks to that one.

Figured, just as well

**Comment by gep13** [comment]
Makes sense to me!
