### ISSUE TITLE
Building fails with latest pre-release because of deleted gitlink package

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#128]
Because version 2.4.1 of the GitLink package have been deleted from nuget.org building on appveyor currently fails when gitlink is enabled and no previous cache exists.

https://ci.appveyor.com/project/AdmiringWorm/cake-transifex/build/0.3.0-alpha.15.build.55#L329

**Comment by pascalberger** [comment]
This should already be fixed with #123.

Make sure to [clean AppVeyor Cache](https://cake-contrib.github.io/Cake.Recipe/docs/usage/cleaning-cache) to use latest version of Cake.Recipe.

**Comment by AdmiringWorm** [comment]
The cache is already clean, it automatically gets invalidated when I change either `setup.cake` or `tools/packages.config` files.

just cleaned the tools directory on my local machine and looked at the `tools.cake` file,
it still references version `2.4.1`.
@gep13 any idea why that would be?

**Comment by gep13** [comment]
@AdmiringWorm how are you referencing the Cake.Recipe NuGet package?  i.e. what `#nuget` are you using at the top of your setup.cake?

I have just downloaded Cake.Recipe `0.3.0-unstable0248` from MyGet and I can confirm that it is correctly referencing the older GitLink:

![image](https://user-images.githubusercontent.com/1271146/28451361-badbd8be-6de4-11e7-826e-10e8caf2e4df.png)

**Comment by AdmiringWorm** [comment]
I see know what I'm doing wrong, I had another look at my setup.cake.

Looks like I'm pulling Cake.Recipe from the wrong repository. I'm pulling from the one I used when working on supporting .NET Core.

Sorry about that.

**Comment by gep13** [comment]
>@AdmiringWorm said...
Sorry about that.

No need to apologise!  Glad you got it sorted out.
