### ISSUE TITLE
Using custom solution file path throws an error when using gitlink

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#129]
When the actual path to the solution file is not inside the specified source directory, build will fail when running gitlink.

For instance in my own repository I keep the solution file in the root of the repository, except for inside the `src` directory where both the source code and the unit tests reside.
This works as expected both when restoring nuget packages, and when building the projects.
However when executing gitlink this fails miserably just after posting the following message:
```
Could not find solution file: C:\projects\cake-transifex\src/Cake.Transifex.sln
```

## Expected
I would expect the call to gitlink uses the same paths as when both when restoring packages, and building the projects.

I won't mind opening a PR for that of course, and keeping it the same as the path used in restore and build.

**Comment by gep13** [comment]
@AdmiringWorm thank you for reporting this, I will try to get to this tomorrow.

**Comment by AdmiringWorm** [comment]
@gep13 I can take care of this when I get home later today if you want

**Comment by gep13** [comment]
@AdmiringWorm that would be great, thank you!

**Comment by gep13** [comment]
@AdmiringWorm thanks for making this fix.
