### ISSUE TITLE
Add support for custom paths to test projects

### ISSUE THREAD

**Issue by RLittlesII** [cake-contrib/Cake.Recipe#132]
Add a build parameter to pass in a custom location for test projects.  Currently it is hard wired to `BuildParameters.SourceDirectoryPath + "/**/*Tests.csproj"` in testing.cake

**Comment by gep13** [comment]
@RLittlesII are you planning on implementing this one?  If so, I can assign you to the issue.

**Comment by RLittlesII** [comment]
@gep13 Yes.  The code is on my PC at home.  I'll submit a WIP PR this evening.

**Comment by gep13** [comment]
@RLittlesII perfect, thank you very much!

**Comment by RLittlesII** [comment]
@gep13 Got slightly carried away.  Added two for the price of one.  Let me know if you want me to change anything.  Tested it from this using the below in my cake file.
`#load nuget:https://www.myget.org/F/rlittlesii-cake-recipe/api/v2?package=Cake.Recipe&prerelease`
