### ISSUE TITLE
Add support for asp.net mvc web projects

### ISSUE THREAD

**Issue by tjackadams** [cake-contrib/Cake.Recipe#134]
I see we have a CreateNuGetPackagesTask and CreateChocolateyPackagesTask but i'm thinking there should be a "CreateWebPackageTask".

It should
1. Detect it is a web project
2. Build the web project
3. Perform any web.config transforms
4. Zip up the project and upload to artifacts if applicable.

Is this something the project would be interested in? If so i can draft up a solution. Thanks!

**Comment by gep13** [comment]
@tjackadams I certainly would have no objections, assuming that it doesn't impact on any of the existing functionality.  To date, the functionality that exists in Cake.Recipe has been directly associated with the types of builds that I use.

**Comment by AdmiringWorm** [comment]
Just throwing my thoughts out there:

Considering what would need to be supported to have support for asp.net mvc, this could be something that would be better suited for a separate Recipe.
While it probably would be possible to support MVC projects in Cake.Recipe, it may cause it to be very bloated depending on which features will be added for it (what you listed is just the absolute basic ones).

IMHO, it would be better to have a different addin specifically targeting web projects (not just MVC, but Web Forms, asp.net core, MVC and Web Pages).

**Comment by gep13** [comment]
@tjackadams Sorry about the delay in replying to this.  I tend to agree with @AdmiringWorm here, and I have done the same thing for when doing VSCode Extension packages.  I would suggest that if this is still something you are interested in, that you look to create a standalone recipe for this.  Some examples can be found here:

https://github.com/cake-contrib/?utf8=%E2%9C%93&q=recipe&type=&language=
