### ISSUE TITLE
Cake.Recipe do not work with cake 0.21.0+

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#136]
Because of the change for the dotnet aliases that was added in cake version 0.21.0, Cake.Recipe do not work with the latest version of cake.

So far, the only thing I noticed that are incompatible is the Verbose value set for the calls to the .NET Core aliases.

**Comment by mholo65** [comment]
@AdmiringWorm do you have time to submit a PR? I know @gep13 is quite busy with other stuff right now.

**Comment by AdmiringWorm** [comment]
@mholo65 I'm about to sign off for tonight, but I can see if I can't get some time before or after work tomorrow.

**Comment by AdmiringWorm** [comment]
not sure what would be the best option though, drop the setting of the Verbose parameter altogether to keep it compatible with users running a lower version of cake, or setting it to the equivalent of what it's now and force users to the latest cake version.

**Comment by mholo65** [comment]
@gep13 any thougths on this? Latest and greatest?

**Comment by gep13** [comment]
@mholo65 for now, I am inclined to say that we remove the property that is causing the problem just now.

In a future version, we can look to controlling the verbosity, which would force users to upgrade to specific version of Cake.
