### ISSUE TITLE
Problem running unit tests

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#137]
Noticed this tonight...

https://ci.appveyor.com/project/cakecontrib/cake-vscode/build/0.8.0-unstable.7.build.36#L615

@pascalberger @AdmiringWorm either of you seen any problems like this?

**Comment by pascalberger** [comment]
@gep13 No never had this

**Comment by gep13** [comment]
Fixed with this build: https://ci.appveyor.com/project/cakecontrib/cake-vscode/build/0.8.0-unstable.7.build.37
