### ISSUE TITLE
Can't specify NuGet feeds

### ISSUE THREAD

**Issue by mholo65** [cake-contrib/Cake.Recipe#138]
DotNetRestore doesn't take `NuGet.Config` into account. Instead NuGet V2 and Cake Contrib feed is hardcoded.

**Comment by gep13** [comment]
@mholo65 what would your suggestion on how this should be handled?

**Comment by mholo65** [comment]
@gep13 keep an option to override to hardcoded sources [here](https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/build.cake#L122) and [here](https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/build.cake#L135).

Regarding respecting `NuGet.Config`, that is however more of an Cake issue. But in `Cake.Recipe` we could add a `ISet<string> NuGetSources` properties to [`ToolSettings`](https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/toolsettings.cake) for manual override.

**Comment by devlead** [comment]
It would be fairly easy to parse Nuget.config if exists and add to sources list.

**Comment by gep13** [comment]
@devlead we accept Pull Requests :-P

**Comment by devlead** [comment]
Actually think I've got some code for that in a build script so I could do that 😎

**Comment by gep13** [comment]
What a guy! 😸

**Comment by devlead** [comment]
@mholo65 #139 addressed this, can you take it for a spin?

**Comment by mholo65** [comment]
@devlead works fine https://github.com/cake-build/bakery/commit/af411f964932cc6791c2ab2aad6855e78ce5513b
