### ISSUE TITLE
Include all available options commented out in setup.cake

### ISSUE THREAD

**Issue by wwwlicious** [cake-contrib/Cake.Recipe#151]
Just a quick documentation suggestion based on my recent experience. 

It would be helpful to include all the available options + sample values commented out the 
default setup.cake file as a quick reference to avoid some grokking of the scripts.

**Comment by gep13** [comment]
@wwwlicious yip, totally agreed.  This is related to this: https://github.com/cake-contrib/Cake.Recipe/issues/36
