### ISSUE TITLE
Support Cake >= 0.22.0

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#159]
Update all addins to version build against Cake 0.22.0

* [x] Cake.CodeAnalysisReporting (Supported since [0.2.0](https://github.com/cake-contrib/Cake.CodeAnalysisReporting/releases/tag/0.2.0))
* [x] Cake.Codecov (https://github.com/cake-contrib/Cake.Codecov/issues/13)
* [x] Cake.Coveralls (Supported since [0.7.0](https://github.com/cake-contrib/Cake.Coveralls/releases/tag/0.7.0))
* [x] Cake.Figlet (Supported since 1.0)
* [x] Cake.Git (Supported since [0.16.0](https://github.com/cake-contrib/Cake_Git/releases/tag/v0.16.0))
* [x] Cake.Gitter (Supported since [0.7.0](https://github.com/cake-contrib/Cake.Gitter/releases/tag/0.7.0))
* [x] Cake.Graph (Supported since [0.3.0](https://github.com/cake-contrib/Cake.Graph/releases/tag/0.3.0))
* [x] Cake.Incubator (https://github.com/cake-contrib/Cake.Incubator/issues/47)
* [x] Cake.Kudu (Supported since [0.5.0](https://github.com/cake-contrib/Cake.Kudu/releases/tag/v0.5.0))
* [x] Cake.MicrosoftTeams (Supported since [0.6.0](https://github.com/cake-contrib/Cake.MicrosoftTeams/releases/tag/v0.6.0))
* [x] Cake.ReSharperReports (Supported since [0.8.0](https://github.com/cake-contrib/Cake.ReSharperReports/releases/tag/0.8.0))
* [x] Cake.Slack (Supported since [0.7.0](https://github.com/cake-contrib/Cake.Slack/releases/tag/v0.7.0))
* [x] Cake.Twitter (Supported since [0.6.0](https://github.com/cake-contrib/Cake.Twitter/releases/tag/0.6.0))
* [x] Cake.Wyam (https://github.com/Wyamio/Wyam/issues/578)

**Comment by gep13** [comment]
This is sort of being tracked here as well:

https://github.com/orgs/cake-contrib/projects/3

With the work that @RLittlesII is doing.

**Comment by pascalberger** [comment]
@gep13 Sure. But I would like to already move to Cake 0.22 if possible, before all addins are ready for .NET Core, therefore the separate issue.

**Comment by gep13** [comment]
@pascalberger yip, understood :+1:

**Comment by AdmiringWorm** [comment]
btw, the upcoming addition of the Cake.Transifex addin to Cake.Recipe already supports 0.22.0+, as well as keeping compatibility with earlier version (except when running Cake CoreCLR)

Just wanted to throw that out there 😄

**Comment by gep13** [comment]
@pascalberger so, in theory, I think we are ready to go with getting this updated, right?

**Comment by AdmiringWorm** [comment]
Just found out today that there are one package missing from this list that isn't compatible.
[Cake.AppVeyor](https://github.com/cake-contrib/Cake.AppVeyor) is still compiled against v 0.17.0, and it isn't possible to target a version earlier than 0.22.0 currently due to other cake addins used (only know of Cake.CodeCov currently).

**Comment by gep13** [comment]
@AdmiringWorm doh! Thanks for pointing that out.  We will have to work with @redth to get that updated.

**Comment by gep13** [comment]
:+1: Perhaps we need a new issue, with another checklist that we can tick off?

**Comment by AdmiringWorm** [comment]
That's my plan, creating the issue at the same time

**Comment by gep13** [comment]
I will close this one again 😄
