### ISSUE TITLE
DirectoryNotFoundException in DotNetCore-Test

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Recipe#160]
I am unable to build my addin on AppVeyor using Cake.Recipe because of several DirectoryNotFound exceptions during the `DotNetCore-Test`. Here are a few examples of the exceptions:
```
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\AdvancedMatcherAttribute.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\AsInterface.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\Capture.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\CaptureMatch.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\ConditionalContext.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\EmptyDefaultValueProvider.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\Evaluator.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\ExpressionExtensions.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\ExpressionStringBuilder.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\Extensions.cs'. 
An System.IO.DirectoryNotFoundException occured: Could not find a part of the path 'C:\projects\moq4\Source\FluentMockContext.cs'. 
```
More available [here](https://ci.appveyor.com/project/cakecontrib/cake-sendgrid/build/0.5.0-rc.2.build.64#L705)

These exceptions, surprisingly,  don't cause the task to fail which is very confusing and they have the side effect of causing a `Could not find a part of the path 'C:\projects\moq4\Source\AdvancedMatcherAttribute.cs'` exception during the  `Upload-Coveralls-Report` task. See example [here](https://ci.appveyor.com/project/cakecontrib/cake-sendgrid/build/0.5.0-rc.2.build.64#L1082).

**Comment by Jericho** [comment]
This is evidently a know issue and there is a [workaround](https://github.com/OpenCover/opencover/issues/731) for OpenCover 4.6.519 

This workaround will no longer be necessary when the next version of OpenCover is released.

**Comment by Jericho** [comment]
@gep13 I'm very frustrated by the issue and determined to find a solution. I'm currently discussing with @sawilde in [issue 771](https://github.com/OpenCover/opencover/issues/771) and hopefully we'll figure out why OpenCover is throwing these exceptions. However, I'm completely baffled by the fact that these exceptions do not cause my Cake task to fail. I would expect Cake to interpret an exception from OpenCover as a sign of failure.

Thanks to a converstation with @pascalberger on gitter on October 20, we were able to determine that this issue seems to be cause by the presence of the `moq` nuget package. The exception go away as soon as I remove the reference to `moq`.

**Comment by Jericho** [comment]
@gep13 UPDATE: I continue to maintain there is an issue in OpenCover that gets triggered by the `moq` nuget package but I have discovered that we can easily workaround it by improving our test coverage filter. We can explicitly exclude moq by adding `-[Moq*]*` (notice the upper case first letter, it's important since, evidently, OpenCover's filtering is case-sensitive. I had previously attempted to exclude `-[moq*]*` and it didn't work) or by using a more targeted initial filter. What I mean is that instead of the default `+[*]*` followed by a few exclusions, all we really need is something like `+[MyLibrary*]* -[*.Tests]*`

I will change my own setup.cake, but do you think we should change the default filter in toolsettings.cake? This is the current default:

```csharp
TestCoverageFilter = testCoverageFilter ?? "+[*]* -[xunit.*]* -[Cake.Core]* -[Cake.Testing]* -[*.Tests]*";
```

**Comment by gep13** [comment]
Let me know what you think the default should be changed to, and we can continue the discussion.

**Comment by Jericho** [comment]
I think it should be:

```csharp
TestCoverageFilter = testCoverageFilter ?? "+[" + projectName + "*]* -[*.Tests]*";
```

`projectName` is just a placeholder, I don't know where this value is stored

**Comment by AdmiringWorm** [comment]
@Jericho the closest would be (I think):
```cs
TestCoverageFilter = testCoverageFilter ?? string.Format("+[{0}*]* -[*.Tests]*", BuildParameters.Title);
```

And I agree, that would be alot better test coverage filter than what the currently default is (that's usually what I have on all of my own projects)

**Comment by Jericho** [comment]
thanks @AdmiringWorm 
@gep13 : I'm submitting a PR with this change

**Comment by Jericho** [comment]
Glad that we can finally close this one for good!
