### ISSUE TITLE
Display version number during setup

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Recipe#168]
It would be great to see something like this:

```
Calculated Semantic Version: 0.5.0
Building version 0.5.0 of Cake.SendGrid (Release, AppVeyor) using version 0.21.1.0 of Cake. (IsTagged: True)
Using Cake.Recipe version x.x.x
```

**Comment by AdmiringWorm** [comment]
I like this, could be helpful for debugging as well.

**Comment by gep13** [comment]
@Jericho @AdmiringWorm you can see this in action here:

https://ci.appveyor.com/project/chocolatey/chocolateygui/build/0.16.0-unstable.81.build.416#L238

![image](https://user-images.githubusercontent.com/1271146/32753027-3c789b4e-c8c3-11e7-9884-358a3c712789.png)
