### ISSUE TITLE
Error when running DupFinder

### ISSUE THREAD

**Issue by phillipsj** [cake-contrib/Cake.Recipe#192]
Here is the error that I keep getting when I run any Jetbrains tools.  I have this error in three different repos.

========================================
DupFinder
========================================
Executing task: DupFinder
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and
 the directory name must be less than 248 characters.
NuGet exited with 1
An error occured while installing package JetBrains.ReSharper.CommandLineTools.
Error: Failed to install tool 'JetBrains.ReSharper.CommandLineTools'.
Deleting file C:/Users/cphil/code/Cake.XdtTransform/e1cd281f-d488-438f-9dda-38d5948c26bc.cake
An error occurred when executing task 'DupFinder'.
Deleting file C:/Users/cphil/code/Cake.XdtTransform/25fdbcd9-6775-461f-8853-02a837c17c5a.cake
Duplicates were found in your codebase, creating HTML report...
Unable to locate Input File

**Comment by phillipsj** [comment]
Same error when executing InspectCode:

========================================
InspectCode
========================================
Executing task: InspectCode
The specified path, file name, or both are too long. The fully qualified file name must be less than 260 characters, and the directory name must be less than 248 characters.
NuGet exited with 1
An error occured while installing package JetBrains.ReSharper.CommandLineTools.
Error: Failed to install tool 'JetBrains.ReSharper.CommandLineTools'.
Deleting file C:/Users/cphil/code/Cake.XdtTransform/cb4d7c3e-cef4-4b6a-b882-555b911e822f.cake
An error occurred when executing task 'InspectCode'.

**Comment by phillipsj** [comment]
I am fixing my repos temporarily by setting the property to disable the execution.

**Comment by devlead** [comment]
Get the same error if you use inproc nuget client?

## Environment Variable Name

```sh
CAKE_NUGET_USEINPROCESSCLIENT
```

## Config File Contents

```sh
[NuGet]
UseInProcessClient=true
```

## Direct Argument

```sh
cake.exe --nuget_useinprocessclient=true
```

**Comment by gep13** [comment]
@phillipsj I am "fairly" sure, that this has been fixed.  As such, I am going to close this off.  Let me know if still an issue.
