### ISSUE TITLE
.\build.ps1 syntax error near unexpected token `newline'

### ISSUE THREAD

**Issue by asterixorobelix** [cake-contrib/Cake.Recipe#212]
I have downloaded the following from this repo:
.appveyor.yml
.gitignore
build.ps1
config.wyam
GitReleaseManager.yaml
setup.cake

I have then modified appveyor and gitignore, but nothing else. When I run:

```powershel
.\build.ps1 -target preview
```

I get the following error:
```powershell
syntax error near unexpected token `newline'
line 7: `<#'
```

**Comment by gep13** [comment]
@asterixorobelix are the files that you are using hosted somewhere, i.e. on a GitHub repository?  If so, can you provide a link?

The files in this repository are being used in a number of different places, so I am reasonably sure that they are working as expected.

**Comment by asterixorobelix** [comment]
@gep13 Hi Gary, thanks for the response.

All the related files are here: https://github.com/asterixorobelix/asterixorobelix.github.io

I am attempting to follow: http://wbates.net/posts/setting-up-a-wyam-blog-with-cake-recipe-and-github-pages

**Comment by asterixorobelix** [comment]
Hi Gary - I have solved some of my problems. 

- You must use powershell and not other command prompts such as [Cmder](http://cmder.net/)
- You need to change the execution policy as discussed [here](https://docs.microsoft.com/en-gb/powershell/module/microsoft.powershell.core/about/about_execution_policies?view=powershell-6&viewFallbackFrom=powershell-Microsoft.PowerShell.Core)

For example: 
```powershell
Set-ExecutionPolicy -Scope CurrentUser -ExecutionPolicy RemoteSigned
```

I am now getting the following error:
```powershell
Error: The assembly 'Cake.Codecov, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null'
is referencing an older version of Cake.Core (0.22.0).
This assembly need to reference at least Cake.Core version 0.26.0.
Another option is to downgrade Cake to an earlier version.
It's not recommended, but you can explicitly opt-out of assembly verification
by configuring the Skip Verification setting to true
(i.e. command line parameter "--settings_skipverification=true",
environment variable "CAKE_SETTINGS_SKIPVERIFICATION=true",
read more about configuration at https://cakebuild.net/docs/fundamentals/configuration)
```

**Comment by asterixorobelix** [comment]
I was able to get a build to work using [this build.ps1 file](https://github.com/cake-build/example/blob/master/build.ps1) and [this build.cake file](https://github.com/daveaglick/daveaglick/blob/master/build.cake) . Does that give you any clues?

**Comment by asterixorobelix** [comment]
Apparently, [Cake must be downgraded to a previous version](https://github.com/cake-contrib/Cake.Codecov/issues/20#issuecomment-379456752). I'm rather at see here, so do you think that someone could point me to how I would go about doing this?

**Comment by asterixorobelix** [comment]
I've setup the packages.config to use a lower Cake version. I've also "un-ignored" the file, so that it gets included by git. The file shows up in the remote repo. Appveyor is picking up the push; but I am now getting the following error during the appveyor build: 
```powershell
========================================
Generate-Version-File
========================================
Executing task: Generate-Version-File
Cake.exe : An error occurred when executing task 'Generate-Version-File'.
At line:1 char:1
+ & "C:\projects\asterixorobelix-github-io\tools\Cake\Cake.exe" "setup. ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (An error occurr...-Version-File'.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
----------------------------------------
Teardown
----------------------------------------
Executing custom teardown action...
Starting Teardown...
Deleting nupkg files...
Deleting file C:/projects/asterixorobelix-github-io/tools/Cake/Cake.nupkg
Finished running tasks.
Error: 
One or more errors occurred.
	
Could not find a part of the path 'C:\projects\asterixorobelix-github-io\Cake.Recipe\Content\version.cake'.
Command executed with exception: Could not find a part of the path 'C:\projects\asterixorobelix-github-io\Cake.Recipe\Content\version.cake'.
```
The project builds when I run:
```powershell
.\build.ps1 -target preview
```
However, it does not actually do the preview behaviour of listening on a localhost port. 

Any ideas?

**Comment by gep13** [comment]
@asterixorobelix looks like you are now using Jekyll for your site, so I am going to go ahead and close this out.

Apologies for not getting back to you about this, looks like it fell under my radar 😢
