### ISSUE TITLE
Be able to override tools version

### ISSUE THREAD

**Issue by skovsende** [cake-contrib/Cake.Recipe#214]
I have a need to override the version of GitVersion defined in tools.cake. Right now the variable GitVersionTool is defined as a const, so I can't change it. A simple solution would be to make the variable non-const so I could start my setup.cake with:

```
#load "nuget:https://www.myget.org/F/cake-contrib/api/v2?package=Cake.Recipe&prerelease"
GitVersionTool = "#tool nuget:?package=GitVersion.CommandLine&version=4.0.0-beta0012";
```

**Comment by devlead** [comment]
This would only work for tools and not addins, but looks like it's tools you want to change, so probably just an typo.

Another way could be to have compiler directives in cake recipe.
```csharp
#if (!CustomGitVersionTool)
private const string GitVersionTool = "#tool nuget:?package=GitVersion.CommandLine&version=3.6.2";
#endif
```
Then you could just 
```csharp
#define CustomGitVersionTool
private const string GitVersionTool = "#tool nuget:?package=GitVersion.CommandLine&version=3.6.2";
```
In your script and it's still const an semantics kept the same.

**Comment by skovsende** [comment]
Yes, indeed I mean tools :) The #define solution is a little more noisy, but I think it's a fine solution to be able to keep it as consts. Can you do compiler directives in cake today?

**Comment by devlead** [comment]
Yes, seems it's not fully documented yet, but been possible for a few versions, example here:
https://github.com/cake-build/cake/blob/develop/tests/integration/Cake.Core/Scripting/DefineDirective.cake

Would also be nice if Cake.Recipe defined a few defines so one could know in a script if running in Recipe or not.

Advantage with constants is that it's easier to debug as they're immutable during whole script execution, and give good compile time checks. One could of course make them get\set, but in that case preferably via the ToolSettings.SetToolSettings method only.

**Comment by AdmiringWorm** [comment]
@devlead just curious, is it also possible to define a directive with a value?
Say for instead something like this:
```cs
#define GitVersionToolVersion "3.6.2"
private const string GitVersionTool = "#tool nuget:?package=GitVersion.Commandline&version=" + GitVersionToolVersion;
```
or even
```cs
#define GitVersionToolVersion "3.6.2"
#define GitVersionSource ""
private const string GitVersionTool = "#tool nuget:" + GitVersionSource + "?package=GitVersion.Commandline&version=" + GitVersionToolVersion;
```

I know this isn't supported in C# itself, and probably would require some custom logic.

**Comment by gep13** [comment]
@admiringworm not sure exactly what you are looking for, but would this help?

https://github.com/cake-build/cake/pull/2023

**Comment by AdmiringWorm** [comment]
@gep13 while that could most likely be used, it's not exactly what I mean.

Think preprocessor defines like those available in the C and C++ languages.
Where you can define a value using a preprocessor directive once, and wherever you use the name of that directive in the code will be replaced with the actual value instead.

for instance (with C#, of course it doesn't work):

Before preprocessor
```cs
#define MyValue "Hey"
#define MyValue2 " Mate"

static void Main()
{
  System.Console.WriteLine(MyValue + MyValue2);
}
```

After processing
```cs
static void()
{
  System.Console.WriteLine("Hey" + " Mate");
}
```

**Comment by skemprunner** [comment]
[cake-build/cake#2023](https://github.com/cake-build/cake/pull/2023) has been resolved, which means there is the option is using an environment variable in tools.cake:
```c#
private const string GitVersionTool = "#tool nuget:?package=GitVersion.CommandLine&version=%GitVersion.CommandLine.Version%";
```

In toolsettings.cake have an extra optional parameter passed into SetToolSettings like gitVersionToolVersion and then call

```c#
System.Environment.SetEnvironmentVariable("GitVersion.CommandLine.Version", gitVersionToolVersion ?? "3.6.5");
```

GitVersion should be the only option worth configuring, since there is are differences between v3 and v4 (current)

**Comment by gep13** [comment]
@skovsende this should now be available in the latest version of Cake.Recipe from the MyGet feed.  In your setup/recipe.cake file, you can now do somethign like the following:

```
ToolSettings.SetToolPreprocessorDirectives(gitVersionTool: "#tool nuget:?package=GitVersion.CommandLine&version=5.0.2-beta1.59&prerelease");
```

To override the preprocessor directive that is used to install the tool being used.
