### ISSUE TITLE
Remove use of deprecated CustomProjectParserResult.OutputPath

### ISSUE THREAD

**Issue by wwwlicious** [cake-contrib/Cake.Recipe#215]
The OutputPath is now deprecated and will be set to throw an exception in a future release prior to being removed altogether.

This is due to the fact that from VS2017 project format onwards, there is no guarantee that a project will have only a single output path due to multi-targeting for frameworks and platforms.

This property has been replaces with a string array `OutputPaths` which will include all project artifact paths (with some edge cases around platform RID's which have not yet stabilized in MSBuild AFAIK)

When looking for artifacts, Receipe should always use the OutputPaths and assume that identically named artifacts may exist within these folders.

Output warnings from typical receipt build FYI
```
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(263,12): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(265,44): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(309,36): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(366,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(375,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(383,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(391,32): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(414,29): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
C:/dev/Cake.Incubator/tools/Cake.Recipe.0.3.0-unstable0371/Content/build.cake(415,36): warning CS0618: 'CustomProjectParserResult.OutputPath' is obsolete: 'Use OutputPaths instead
for multi-targeting support'
Printing Build Parameters...

```

**Comment by AdmiringWorm** [comment]
I'm curious, for projects not targeting .NET Core, and those not using VS 2017+ Project format. Will the `OutputPaths` property only contain 1 path?
If so, I believe the necessary modification to the recipe would be minimal, as we only need to pick the first path (.NET Core and VS2017+ projects already use `OutputPaths`).

Would appreciate it if anyone knew, and could let us know.

**Comment by wwwlicious** [comment]
@AdmiringWorm Yes. Pre vs2017 and single target projects will have one entry in OutputPaths.

Recipe however needs to handle one or more output paths. For example, I don't think it handles copying test project outputs with more than one target framework currently. 

General rule of thumb is you should treat the compiler output as an array of locations, hence the change in project parsing result.

**Comment by AdmiringWorm** [comment]
@wwwlicious you are correct, it don't handle copying unit test projects with multiple output paths.

I'm looking into this issue, and trying to find a more general aproach to how it is currently implemented (which of course will be changed to use outputpaths).
