### ISSUE TITLE
Versioning - Add overridable build parameter task to generate versioning information

### ISSUE THREAD

**Issue by gjonespf** [cake-contrib/Cake.Recipe#217]
Thinking of being able to do something like this:
```
BuildParameters.Tasks.GenerateVersioning.Task.Actions.Clear();
BuildParameters.Tasks.GenerateVersioning
	.Does(() => {
		Information("Add manual versioning here");
	});
```
This would enable you to build custom versioning schemes, use other tools as dropin replacements for GitVersion, or customise the GitVersion options completely.

**Comment by gep13** [comment]
Comment from @AdmiringWorm in duplicate issue...

Or maybe in a Setup<BuildVersion> instead, which can be conditionally disabled by the user if they want.
ie

```
#if !CUSTOM_VERSIONING
Setup<BuildVersion>((context) => {
  var version = new BuildVersion();

  // Do necessary logic for using versioning with gitversion

  return version;
});
#endif
```
