### ISSUE TITLE
Link entries in issue report to files

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#239]
Entries in issue report should link to files on hosting provider. Script should detect if any of the supported hosting providers (currently GitHub, TFS/VSTS) is used use the appropriate file link settings.

See [Demo](https://cake-contrib.github.io/Cake.Issues.Website/docs/report-formats/generic/templates/htmldxdatagrid-demo-filelinking.html) and [Source Code](https://github.com/cake-contrib/Cake.Issues.Reporting.Generic/blob/develop/demos/build/create-reports/create-reports-htmldxdatagrid-file-linking.cake)

**Comment by gep13** [comment]
@pascalberger now that we are using Cake.Issues.Recipe, how would we go about doing this?  Or is this now already being done?

**Comment by pascalberger** [comment]
Cake.Issues.Recipe doesn't support this yet. But it definitely should be implemented there and not here. There's already an issue for this: https://github.com/cake-contrib/Cake.Issues.Recipe/issues/20

I would suggest to close the issue here.

**Comment by gep13** [comment]
@pascalberger agreed, thanks for confirming!
