### ISSUE TITLE
Using of Cake.Recipe is tightly coupled with AppVeyor

### ISSUE THREAD

**Issue by vhatsura** [cake-contrib/Cake.Recipe#259]
Hi, guys!

Big thanks for Cake.Recipe which is really simplify CI configuration.

However, as I see, Cake.Recipe has some limitations, such as tightly coupled with AppVeyor CI:

https://github.com/cake-contrib/Cake.Recipe/blob/eed2a052755dbd47e777796b0d7f13276cb5542c/Cake.Recipe/Content/parameters.cake#L508

@RLittlesII already raised issue related to this (#188), but I suggest to create a generic CIProvider, which will hide a really Build system Provider.

What do you think about it?

**Comment by pascalberger** [comment]
We're definitely interested in having full support for different build servers inside Cake.Recipe. In the future we would like to give addin authors, which are hosting their addin inside the cake-contrib organization, the option to use Azure Pipeline builds additional to AppVeyor (as this for example would give us more parallel build pipelines), and as most of them are using Cake.Recipe this would require some work to abstract the build system integration.

That said I cannot give you an estimated time when this will be finished, as people working on this only have a limited amount of time. If you're interested in contributing, we would be happy to discuss possible implementations and accept PRs.

**Comment by gep13** [comment]
@vhatsura I have merged in your work in #373 and I have also taken the steps to rename the top level AppVeyor task to be ContinuousIntegration instead.  There may well be some tidy up that needs to happen for everything to work properly, but could I ask you to take the latest pre-release version of Cake.Recipe for a spin on your Azure Pipelines, to see if they are working as you would expect.

**Comment by gep13** [comment]
Cake.Recipe now supports running on AppVeyor, TeamCity, Azure Pipelines, Travis CI and of course locally on a developer machine.  I think we can go ahead and close this out.
