### ISSUE TITLE
System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.

### ISSUE THREAD

**Issue by tjackadams** [cake-contrib/Cake.Recipe#269]
Hello,

i have a .net 4.5.2 project for which i was using this build tool.
The project has started failing to build with Cake.Recipe now, however works perfectly fine with Visual Studio.
I haven't committed to the project in a while so i understand that quite a lot might have changed and it may just be a case of updating my config.

Here is the Stack Trace of the exception

> ----------------------------------------
> Teardown
> ----------------------------------------
> Executing custom teardown action...
> Starting Teardown...
> Deleting nupkg files...
> Deleting file C:/Users/tjack/source/repos/CentralTechnology/lms-agent/tools/Cake/Cake.nupkg
> Finished running tasks.
> Error: System.AggregateException: One or more errors occurred. ---> System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: message
>    at Cake.Issues.IssuesArgumentChecks.NotNullOrWhiteSpace(String value, String parameterName) in C:\projects\cake-issues\src\Cake.Issues\IssuesArgumentChecks.cs:line 47
>    at Cake.Issues.IssueBuilder.NewIssue[T](String message, T issueProvider) in C:\projects\cake-issues\src\Cake.Issues\IssueBuilder.cs:line 80
>    at Cake.Issues.MsBuild.LogFileFormat.XmlFileLoggerLogFileFormat.ReadIssues(MsBuildIssuesProvider issueProvider, IssueCommentFormat format, RepositorySettings repositorySettings, MsBuildIssuesSettings issueProviderSettings) in C:\projects\cake-issues-msbuild\src\Cake.Issues.MsBuild\LogFileFormat\XmlFileLoggerLogFileFormat.cs:line 75
>    at Cake.Issues.BaseMultiFormatIssueProvider`2.InternalReadIssues(IssueCommentFormat format) in C:\projects\cake-issues\src\Cake.Issues\BaseMultiFormatIssueProvider.cs:line 28
>    at Cake.Issues.IssuesReader.ReadIssues(IssueCommentFormat format) in C:\projects\cake-issues\src\Cake.Issues\IssuesReader.cs:line 56
>    at Submission#0.ReadIssues(IIssueProvider issueProvider, DirectoryPath repositoryRoot)
>    at Submission#0.<>c__DisplayClass0_1.<<Initialize>>b__110()
>    at Submission#0.<<Initialize>>b__0_84(String tool, Action action)
>    at Submission#0.<<Initialize>>b__0_21(BuildData data)
>    at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x)
>    at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__30.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
>    at Submission#0.<get_Build>b__555_0(String target)
>    at Submission#0.Builder.Run()
>    at Submission#0.<<Initialize>>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
>    at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
>    at Cake.Scripting.Roslyn.RoslynScriptSession.Execute(Script script)
>    at Cake.Core.Scripting.ScriptRunner.Run(IScriptHost host, FilePath scriptPath, IDictionary`2 arguments)
>    at Cake.Commands.BuildCommand.Execute(CakeOptions options)
>    at Cake.CakeApplication.Run(CakeOptions options)
>    at Cake.Program.Main()
> ---> (Inner Exception #0) System.ArgumentOutOfRangeException: Specified argument was out of the range of valid values.
> Parameter name: message
>    at Cake.Issues.IssuesArgumentChecks.NotNullOrWhiteSpace(String value, String parameterName) in C:\projects\cake-issues\src\Cake.Issues\IssuesArgumentChecks.cs:line 47
>    at Cake.Issues.IssueBuilder.NewIssue[T](String message, T issueProvider) in C:\projects\cake-issues\src\Cake.Issues\IssueBuilder.cs:line 80
>    at Cake.Issues.MsBuild.LogFileFormat.XmlFileLoggerLogFileFormat.ReadIssues(MsBuildIssuesProvider issueProvider, IssueCommentFormat format, RepositorySettings repositorySettings, MsBuildIssuesSettings issueProviderSettings) in C:\projects\cake-issues-msbuild\src\Cake.Issues.MsBuild\LogFileFormat\XmlFileLoggerLogFileFormat.cs:line 75
>    at Cake.Issues.BaseMultiFormatIssueProvider`2.InternalReadIssues(IssueCommentFormat format) in C:\projects\cake-issues\src\Cake.Issues\BaseMultiFormatIssueProvider.cs:line 28
>    at Cake.Issues.IssuesReader.ReadIssues(IssueCommentFormat format) in C:\projects\cake-issues\src\Cake.Issues\IssuesReader.cs:line 56
>    at Submission#0.ReadIssues(IIssueProvider issueProvider, DirectoryPath repositoryRoot)
>    at Submission#0.<>c__DisplayClass0_1.<<Initialize>>b__110()
>    at Submission#0.<<Initialize>>b__0_84(String tool, Action action)
>    at Submission#0.<<Initialize>>b__0_21(BuildData data)
>    at Cake.Core.CakeTaskBuilderExtensions.<>c__DisplayClass20_0.<Does>b__0(ICakeContext x)
>    at Cake.Core.CakeTask.<Execute>d__43.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.DefaultExecutionStrategy.<ExecuteAsync>d__4.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.CakeEngine.<ExecuteTaskAsync>d__30.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.CakeEngine.<RunTargetAsync>d__27.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Scripting.BuildScriptHost.<RunTargetAsync>d__3.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Cake.Core.Scripting.ScriptHost.RunTarget(String target)
>    at Submission#0.<get_Build>b__555_0(String target)
>    at Submission#0.Builder.Run()
>    at Submission#0.<<Initialize>>d__0.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.CodeAnalysis.Scripting.ScriptExecutionState.<RunSubmissionsAsync>d__9`1.MoveNext()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Microsoft.CodeAnalysis.Scripting.Script`1.<RunSubmissionsAsync>d__21.MoveNext()<---

Here is my setup.cake file. I've stripped this down to try and diagnose the issue.

```
#load nuget:https://www.myget.org/F/cake-contrib/api/v2?package=Cake.Recipe&prerelease

Environment.SetVariableNames();

BuildParameters.SetParameters(
	context: Context,
	buildSystem: BuildSystem,
	sourceDirectoryPath: "./src",
	title: "LicenseMonitoringSystem",
	treatWarningsAsErrors : false
);

BuildParameters.PrintParameters(Context);

Build.Run();
```

And my packages.config

```
<?xml version="1.0" encoding="utf-8"?>
<packages>
	<package id="Cake" version="0.28.0" />
</packages>

```

Any help is appreciated!

**Comment by pascalberger** [comment]
Which version of Cake.Recipe are you using? Would it be possible for you to share the `\BuildArtifacts\MsBuild.log` file?

**Comment by tjackadams** [comment]
[MsBuild.log](https://github.com/cake-contrib/Cake.Recipe/files/2571404/MsBuild.log)

if the folder name is the version then i am using Cake.Recipe.0.3.0-unstable0415

**Comment by pascalberger** [comment]
Thanks. The issue is this warning which doesn't contain a message:

```
<warning file="EXEC" line="0" column="0" started="12/11/2018 09:23:43" />
```

I'll fix this in the upstream Cake addin, to filter out any warnings which don't contain a message and update in Cake.Recipe.

**Comment by pascalberger** [comment]
@tjackadams Can you please try again with the latest release from MyGet (`0.3.0-unstable0417`) and reopen the issue if it still doesn't work

**Comment by tjackadams** [comment]
@pascalberger all seems to be working now. Many thanks!
