### ISSUE TITLE
Fix issue with replacing Cake.Recipe for integration tests

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#306]
Integration Tests extract latest content into the `Cake.Recipe` folder, but in-proc NuGet Client restores into a versioned number folder:

![image](https://user-images.githubusercontent.com/1271146/50059471-26816780-017f-11e9-88d3-6b1293b5b507.png)

Not immediately clear on what can be done to resolve this.

@mholo65 did you have any ideas here?  Is there a way to tell the in-proc NuGet client to NOT do anything?

**Comment by mholo65** [comment]
@gep13, no there’s no way to do that, as this is a functionality of NuGet itself.

What you want to do is to install Cake.Recipe from local source in integration tests. Take a look at Bakery integration tests, we do that there as well.

**Comment by gep13** [comment]
For reference...

https://github.com/cake-build/bakery/blob/develop/setup.cake#L214

**Comment by gep13** [comment]
This has been fixed, as discussed on live stream on the topic.

The integration tests now update the setup/recipe .cake file for the test repository, to restore Cake.Recipe from a file:// location, rather than from NuGet.  That means, the version of Cake.Recipe that was just built is what is used for testing.
