### ISSUE TITLE
Disable task graphs in documentation by default

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#359]
Having documentation for build script tasks makes only sense for Recipe like NuGet packages, but not for all other projects using Cake.Recipe. To have this disabled by default and explicitely enabled for Cake.Recipe would make more sense therefore.

**Comment by gep13** [comment]
Initially, we were hoping to only disable Cake.Graph from being enabled by default, however, we ran into a number of problems with getting the build to work when a dependency brought in by Cake.Graph was being used.  In the end, we had to remove Cake.Graph completely, which was done as part of this commit:

https://github.com/cake-contrib/Cake.Recipe/commit/b451ede6d929fe4770b259e53eb757d82e5e07ee

We may look at bringing this back in the future, but for now, it has been removed.
