### ISSUE TITLE
Use msbuild on unix when it is installed

### ISSUE THREAD

**Issue by Cheesebaron** [cake-contrib/Cake.Recipe#379]
xbuild isn't capable of building anything new, such as projects using the SDK style csproj files. It hasn't been necessary to use xbuild on macOS for a very long time. The only reason you would use it, would be to get it to color the build output.

Please switch to msbuild also when not running on windows: https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/build.cake#L173

**Comment by gep13** [comment]
@AdmiringWorm would you be up for taking a stab at this one as well?

**Comment by AdmiringWorm** [comment]
Sure, I can do that

**Comment by AdmiringWorm** [comment]
This issue may have to be postponed again, depending on the outcome of issue #552 .
Currently, it is not possible to run Cake.Recipe on Unix with the current codebase

**Comment by gep13** [comment]
@AdmiringWorm as discussed on Gitter, we have pinned to 5.0.1 of GitVersion.Commandline, so running on Unix should now get passed the GitVersion execution errors, and hopefully allow answering some of the other remaining questions about running msbuild/xbuild.
