### ISSUE TITLE
Update Cake.Graph to version 0.8.0

### ISSUE THREAD

**Issue by phillipsj** [cake-contrib/Cake.Recipe#381]
This version supports .NET Standard 2.0 and has the correct list of dependencies in the Nuget package.

**Comment by Jericho** [comment]
FYI: this will be taken care of automatically by the AddinDiscoverer. When all addins referenced by Cake.Recipe support Cake 0.33.0 the automated tool will submit a PR to upgrade all addins at once and also update the version of Cake used to build Cake.Recipe.

The progress is monitored in #313. As of this writing, only one addin is preventing upgrading to 0.33.0: Cake.AppVeyor.
