### ISSUE TITLE
Reference to tool codecov in tools.cake needs to be updated

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Recipe#392]
Reference to codecov 1.4.0 in tools.cake should be updated to 1.7.0

**Comment by Jericho** [comment]
This issue was created by mistake while I was investigating an issue in the Cake.AddinDiscoverer tool. Please ignore.

**Comment by AdmiringWorm** [comment]
THis should still be updated 😄

**Comment by Jericho** [comment]
It's blocked by #368. AddinDiscoverer does not suggest upgrading a tool reference when a previous issue+pullrequest is still open.

**Comment by AdmiringWorm** [comment]
@Jericho I am aware of the existing issue+PR.

I just said that because this issue was opened by a mistake.
