### ISSUE TITLE
Move execution of GitVersion to a task

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#449]
Rather than in the Setup which is where it currently is.  This will make it easier for folks to not use GitVersion, in favour of another tool, i.e. RepoVersion, or NerdBank.GitVersioning, etc.

**Comment by AdmiringWorm** [comment]
Or maybe in a `Setup<BuildVersion>` instead, which can be conditionally disabled by the user if they want.
ie

```cs
#if !CUSTOM_VERSIONING
Setup<BuildVersion>((context) => {
  var version = new BuildVersion();

  // Do necessary logic for using versioning with gitversion

  return version;
});
#endif
```

**Comment by AdmiringWorm** [comment]
Btw, wouldn't this be more or less covered by the issue #217

**Comment by gep13** [comment]
@AdmiringWorm you are correct, this is a duplicate.
