### ISSUE TITLE
429 Conflict when pushing packages

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#492]
This occurred on a release build here:

https://ci.appveyor.com/project/GitTools/gitreleasemanager/builds/28976736#L1163

When running a tagged build, publishing to prerelease sources shouldn't be carried out.

**Comment by AdmiringWorm** [comment]
@gep13 I was looking at this issue, but it seems the necessary code has already been implemented:
https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/packages.cake#L147

**Comment by gep13** [comment]
@AdmiringWorm yes, I believe you are right!
