### ISSUE TITLE
Publish notifications to Mastodon as well

### ISSUE THREAD

**Issue by MihaMarkic** [cake-contrib/Cake.Recipe#510]
Since there is now Cake.Mastodon addin, the notifications can be pushed to it as well. A Mastodon account for cake-contrib would be required.
Should I try to implement it?

**Comment by gep13** [comment]
>@MihaMarkic said...
Should I try to implement it?

I personally would have no objections to you adding this.

**Comment by MihaMarkic** [comment]
@AdmiringWorm I've created most of the required code I think. Looks a niche but welcome feature to me.

**Comment by nils-a** [comment]
Since https://twitter.com/TwitterDev/status/1621026986784337922, this "niche" feature has gained a bit of "main stream" 😀 .
