### ISSUE TITLE
Don't have Symbols as false when running nuget pack

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#518]
Currently, when running nuget pack, symbols are turned off, but they are on when running dotnet pack.  These should both be the same, and controlled via a build parameter.

**Comment by AdmiringWorm** [comment]
Be mindful that just enabling symbols for nuget do not enable `snupkg` symbol packages, a custom argument would also be needed (the same can be true for .NET Core tools as well, unless symbol format is specified in project files).

I don't remember at the top of my head what the custom argument was again, but I can find out when it is necessary.

**Comment by AdmiringWorm** [comment]
@gep13 was looking through some of my old issues, isn't this issue a duplicate of #112?

**Comment by gep13** [comment]
Yes, I believe you are right, I will close this one as a duplicate.
