### ISSUE TITLE
Messages sent twice to Gitter while using integration tests

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#528]
Cake.Issues.Recipe uses an [integration test script](https://github.com/cake-contrib/Cake.Issues.Recipe/blob/develop/recipe.cake#L17) which is called from [AppVeyor](https://github.com/cake-contrib/Cake.Issues.Recipe/blob/develop/.appveyor.yml#L13). This results in messages being sent twice to Gitter for release builds: Once for the actual [build](https://ci.appveyor.com/project/cakecontrib/cake-issues-recipe/builds/33916102#L824) and once for [integration tests](https://ci.appveyor.com/project/cakecontrib/cake-issues-recipe/builds/33916102#L1818).

**Comment by gep13** [comment]
This was confirmed as working by @pascalberger
