### ISSUE TITLE
Create build provider for GitHub Actions

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#531]
As there are already a few build providers supporting different CI systems, it would also be helpful to create a provider specifically for GitHub Actions.

**Comment by gep13** [comment]
@AdmiringWorm this would be a great addition, yes!

I believe I am right in saying that @ecampidoglio is working on providing Build System support for GitHub Actions, which would go into Cake as well.

**Comment by AdmiringWorm** [comment]
@gep13 there is already support for GitHub Actions in Cake: https://cakebuild.net/api/Cake.Common.Build/BuildSystem/67BC0EC9

Not sure when it was added, but I do use it in a different project of mine.

**Comment by AdmiringWorm** [comment]
Added in `0.38.0` it seems: https://cakebuild.net/blog/2020/05/cake-v0.38.0-released

**Comment by gep13** [comment]
Hmm, interesting...

I was going off of this comment:

https://github.com/cake-build/cake/issues/2609#issuecomment-653494387

**Comment by AdmiringWorm** [comment]
I am reading that one as additional enhancements to the support that was added in 0.38.0 (I could of course be wrong).

Adding additional helpers such as uploading artifacts, formatting log output and such.

**Comment by gep13** [comment]
@AdmiringWorm it could well be.  I just remember seeing the comment, and I didn't recall that there was a GitHub Action Build System that had been added, so I jumped to a conclusion.

**Comment by ecampidoglio** [comment]
The [`IGitHubActionsProvider`](https://github.com/cake-build/cake/blob/develop/src/Cake.Common/Build/GitHubActions/IGitHubActionsProvider.cs) was added as part of the [0.36.0](https://cakebuild.net/blog/2020/01/cake-v0.36.0-released) release (cake-build/cake@78fe775). However, it only supports reading information from the GitHub Actions environment.

I'm currently adding the ability to send [workflow commands](https://docs.github.com/en/actions/reference/workflow-commands-for-github-actions) from a Cake script.

**Comment by gep13** [comment]
@ecampidoglio thanks for confirming!
