### ISSUE TITLE
Allow ability to override check for supported Cake version

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#536]
Currently getting this error:

![image](https://user-images.githubusercontent.com/1271146/86970052-ac507380-c166-11ea-9063-7922dee2dab4.png)

When trying to test out some things with the latest Cake bits. Need the ability to override this, for testing purposes.

**Comment by AdmiringWorm** [comment]
I would like to look into adding this improvement if that would be okay.
