### ISSUE TITLE
GitVersion.CommandLine can not be run on Unix platforms

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#552]
The latest versions of the package [`GitVersion.CommandLine`](https://www.nuget.org/packages/GitVersion.CommandLine/) is packaged as a standalone .NET Core windows application and as such can not be run on Unix platforms (at least not without some kind of emulation).

As such we need to make a decision on where to progress with this one:

1. Downgrade GitVersion to a version that can be run through mono on Unix (probably GitVersion 4.x or 3.x)
2. Remove GitVersion.CommandLine, and force the usage of GitVersion.Tool (would require .NET Core installed).
3. Remove support for Unix altogether until we can do a .NET Core only builds (I am against this).
4. See if it is possible to emulate the GitVersion runs through a Windows emulator (something along running it through Wine perhaps, not looked into this).

**Comment by gep13** [comment]
@AdmiringWorm I have tested running on my Mac, and it works if we pin to `5.0.1` of GitVersion.Commandline.

**Comment by gep13** [comment]
@AdmiringWorm personally, I would say that we should pin to the above.  It was only recently that this was changed, and I upgraded without testing during this commit:

https://github.com/cake-contrib/Cake.Recipe/commit/f9c520353f8813149c01caf862ede1beb89965c5#diff-bf5cbc5d7820a44e88abfc260484c623

So I don't think there is any harm in reverting to the previous version.

**Comment by AdmiringWorm** [comment]
@gep13 yeah, we can give it a shot.
Although, I will miss some of the new features and bug fixes that went in after it.
But oh well.
A user can still always just override it.

**Comment by gep13** [comment]
>@AdmiringWorm said...
A user can still always just override it.

That is true.  Better to have things work out of the box, with the option to override it.
