### ISSUE TITLE
Remove usage of ReSharperReports

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#557]
This tool is currently used to convert the output from DupFinder into a report which can be easily viewed.

ReSharperReports can also convert the output from InspectCode into a viewable report as well, however, this is now handled by Cake.Issues.

There is a new addin for Cake.Issues, https://github.com/cake-contrib/Cake.Issues.DupFinder which will mean that Cake.Issues will also be able to work with DupFinder.

Due to this, and also the fact that there are no plans to make ReSharperReports run on .Net Core, I am going to suggest that we remove it, and bring in Cake.Issues addin when it is ready.

**Comment by pascalberger** [comment]
For reference: Upstream issue for having support for DupFinder in Cake.Issues.Recipe is https://github.com/cake-contrib/Cake.Issues.Recipe/issues/110
