### ISSUE TITLE
Create log file when running dotnet build

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#568]
Currently when running dotnet build through Cake.Recipe, we do not log any output to file.

This seems like it can be done with the following answer on StackOverflow: https://stackoverflow.com/a/48561727
This would be useful to have when reporting issues together with Cake.Issues.Recipe.

This may perhaps apply to dotnet restore, dotnet test, dotnet publish and dotnet package as well.

**Comment by AdmiringWorm** [comment]
There do not seem to be any XML Logging support for `dotnet build` (not that I could find), and we need to use the binary logger instead. Unfortunately, the file format version used by `dotnet build` is not supported by `Cake.Issues.MsBuild`.

As such I am moving this issue away from the 2.0.0 milestone until there is support.

Cross-reference: https://github.com/cake-contrib/Cake.Issues.MsBuild/issues/178

**Comment by pascalberger** [comment]
Issue for using binary logging in Cake.Recipe is: https://github.com/cake-contrib/Cake.Recipe/issues/252

**Comment by gep13** [comment]
@pascalberger @AdmiringWorm should we close one of these issues as a duplicate?

**Comment by AdmiringWorm** [comment]
@pascalberger @gep13 I was more under the impression for the other issue that it was for non-netcore builds which already have logging functionality.

While the netcore builds don't have any logging functionality at all, while both are related I do not see them as a duplicate as they are for different areas.

**Comment by AdmiringWorm** [comment]
I am taking another stab at this one, as I think I have found a way to generate a binary log file by re-using the StructuredLogger provided by `Cake.Issues.MSBuild`.
