### ISSUE TITLE
When using github token a username is still required when running GitReleaseManager

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#583]
When trying to run GitReleaseManager through Cake.Recipe using PAT, Cake.Recipe expects a username also to be available.

This is never used when using a PAT, but only when specifying a GitHub password, so this requirement should not be needed.

I could not find any instances in Cake.Recipe that uses the GitHub username when a token is specified. As such, I would recommend removing this requirement in these cases.

/cc @gep13

**Comment by gep13** [comment]
Looking at the code, I don't see why a Username would be requried:

https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/gitreleasemanager.cake#L19

But I must be missing something.

Will check in more detail later.

**Comment by AdmiringWorm** [comment]
It isn't required (afaik) anywhere except in the check here: https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/parameters.cake#L172-L173 which requires the username or it won't run GRM no matter if a password or a token is being used.

**Comment by gep13** [comment]
Doh! That check is wrong. We can fix that up.

**Comment by AdmiringWorm** [comment]
Seems to have been an oversight in the PR: https://github.com/cake-contrib/Cake.Recipe/pull/453

As that was merged in for 2.0.0, I am not sure if we need to have this on the 2.0.0 milestone?
