### ISSUE TITLE
Support passing argument to toggle between stable and pre-release release notes

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#597]
In the current stable release of cake.recipe release notes are always created using a MajorMinorPatch version, however, in the latest development version, it is created using a SemVer version instead.

Instead of having the ability to only use 1 or the other, I suggest adding support for a specific argument that can be passed when running the cake script to select whether semver or majorminorpatch version should be used for the milestone.

As an example:
Creating release notes without a specific argument, would use MajorMinorPatch as the default (to keep it backward compatible), but running the cake script with something along the lines of `--create-pre-release` would use a semantic version instead (ie `1.0.0-beta.1`).

**Comment by gep13** [comment]
@AdmiringWorm this sounds like the correct path forward.  Were you wanting to take a stab at this?

**Comment by AdmiringWorm** [comment]
> Were you wanting to take a stab at this?

Yeah, most likely, either during the weekend or sometime next week.
I didn't want to assign myself until I start working on it, as it should be quite simple to implement, and I want to allow other people the opportunity to add the feature if they wish to help out.

**Comment by gep13** [comment]
@AdmiringWorm makes sense!  Thanks

**Comment by AdmiringWorm** [comment]
I have started looking into this request now.
