### ISSUE TITLE
Allow disabling or overriding the framework path override

### ISSUE THREAD

**Issue by AdmiringWorm** [cake-contrib/Cake.Recipe#598]
When running a .NET Core build on Unix system we always add a framework path override.
In some cases, this may be undesirable (like if the projects have the .NET Framework assembly references).

I would suggest allowing this ability to be disabled, and optionally be allowed to pass in a different path to use instead (would be required when cake.recipe support .NET Core only builds).

**Comment by gep13** [comment]
@AdmiringWorm this sounds like a good idea to me.  Is this something that you wanted to take a stab at?

**Comment by AdmiringWorm** [comment]
> Were you wanting to take a stab at this?

Yeah, most likely, either during the weekend or sometime next week.
I didn't want to assign myself until I start working on it, as it should be quite simple to implement, and I want to allow other people the opportunity to add the feature if they wish to help out.
