### ISSUE TITLE
Allow specifying which CI platform should be used for publishing

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#599]
At the minute, the decision on whether a publishing task (such as closing the GitHub Release) is done based on the following:

```
        ShouldPublishGitHub = (!IsLocalBuild &&
                                !IsPullRequest &&
                                IsMainRepository &&
                                (BuildParameters.BranchType == BranchType.Master || BuildParameters.BranchType == BranchType.Release || BuildParameters.BranchType == BranchType.HotFix) &&
                                IsTagged &&
                                shouldPublishGitHub);
```

It is based on criteria such as not being a local build.  However, depending on the setup of the build, you could be running multiple CI systems, AppVeyor, Azure DevOps, GitHub Actions, as well as running on multiple OS'es.  Based on the above criteria, there would be collisions or errors when the publishing steps are ran.

You "can" prevent this by not adding the required environment variables to the CI systems, so that it only happens on the correct one, however, I think it should be clearer.

I am envisioning the usage of two enums to capture the preferred CI provider and operating system, that should be used to do the publishing steps.

@AdmiringWorm thoughts?

**Comment by AdmiringWorm** [comment]
I like the idea, it definitely sounds worthwhile to me.
There may be a need to only do partial publishing steps as well, but that would be a different issue and a task for another time.

> You "can" prevent this by not adding the required environment variables to the CI systems, so that it only happens on the correct one, however, I think it should be clearer.

You also *"can"* add custom criteria to each build task, but that requires a deeper understanding of Cake.Recipe and Cake itself. But just wanted to mention it.
