### ISSUE TITLE
Provide task to download icon for embedding into NuGet package

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#613]
This will be especially useful for places like the Cake-Contrib organisation, that creates lots of packages that are published to NuGet.org.  Rather than replicating the icon into each repository, or using a technique like git submodules to include the icon, provide a task which will fetch the icon to a defined location, which can then be used as part of the build.

This task should:

* not run be default, it should be opted into
* accept a parameter for the URL of where to download the icon from (default to Cake-Contrib icon)
* accept a parameter for the name of the saved file
* accept a parameter for where the icon should be saved (default to known location best for Cake-Contrib projects)
* provide another task to delete the icon (this should be a top level task with no dependents)

**Comment by gep13** [comment]
@AdmiringWorm what are your thoughts on this one?

**Comment by Jericho** [comment]
This task should also validate that csproj/nuspec is properly referencing this icon.

**Comment by gep13** [comment]
Ooo, that is an interesting idea!

**Comment by AdmiringWorm** [comment]
As long as it is kept as on opt-in, then I don't have any issues regarding this feature.

**Comment by gep13** [comment]
I am going to close this issue out, in favour of what is being discussed here:

https://github.com/cake-contrib/Home/issues/11

This seems like a better approach going forward.
