### ISSUE TITLE
For release branches there's a conflict while publishing NuGet package

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#616]
Using Cake.Recipe 2.0.0-alpha0319 I get the following error after running builds for subsequent commits on a release branch:

```
Pushing C:/projects/cake-issues-reporting-generic/BuildArtifacts/Packages/NuGet/Cake.Issues.Reporting.Generic.0.9.0-beta0002.nupkg to PreRelease Source with Url https://pkgs.dev.azure.com/cake-contrib/Home/_packaging/addins/nuget/v3/index.json...
Pushing Cake.Issues.Reporting.Generic.0.9.0-beta0002.nupkg to 'https://pkgs.dev.azure.com/cake-contrib/b0c78987-6a6a-43a7-840a-20702ebe73ac/_packaging/28a780f3-52df-48a7-8220-17568c45552d/nuget/v2/'...
  PUT https://pkgs.dev.azure.com/cake-contrib/b0c78987-6a6a-43a7-840a-20702ebe73ac/_packaging/28a780f3-52df-48a7-8220-17568c45552d/nuget/v2/
  Conflict https://pkgs.dev.azure.com/cake-contrib/b0c78987-6a6a-43a7-840a-20702ebe73ac/_packaging/28a780f3-52df-48a7-8220-17568c45552d/nuget/v2/ 2095ms
To skip already published packages, use the option -SkipDuplicate
Cake.exe : Response status code does not indicate success: 409 (Conflict - The feed already contains 'Cake.Issues.Reporting.Generic 0.9.0-beta0002'. (DevOps Activity ID: 44612550-C113-4AE8-97DF-89388087E4AE)).
```

See [Log](https://ci.appveyor.com/project/cakecontrib/cake-issues-reporting-generic/builds/34560764#L774)

**Comment by gep13** [comment]
@pascalberger just seeing this one now.  This really comes down to the configuration of GitVersion I think.  How would you see this being resolved?

**Comment by pascalberger** [comment]
Having the first build with a version number published and subsequent ones skipped doesn't seem like a good option to me. If we're going to publish CI package for every version, version numbers should be unique for every build IMHO.

**Comment by AdmiringWorm** [comment]
I would suggest making use of the `SkipDuplicate` property on the `NuGetPushSettings` class.
However, I am not sure what approach would be most appropriate in this case.
Could just blindly set it no matter what, make it a global configuration variable or making it configurable per package provider.

**Comment by pascalberger** [comment]
But is it really helpful if you have a CI package available for the first build with a specific version, but not from any subsequent builds? IMHO this is just confusing

**Comment by gep13** [comment]
@pascalberger I believe this has been addressed, and we also discussed the other issue we spoke about on tonights stream, but I think that will need additional testing.
