### ISSUE TITLE
Publish all artifacts to AppVeyor for PRs

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#62]
Currently only NuGet or Chocolatey packages are published to AppVeyor builds as artifacts.

Wouldn't it make sense to have other artifacts like Inspect Code or DupFinder results, Coverage and Test report also published as artifacts?

**Comment by gep13** [comment]
@pascalberger yes, I think that would make sense.

**Comment by gep13** [comment]
@AdmiringWorm don't suppose you would have a list of files that you would like to see added as artifacts?

**Comment by gep13** [comment]
Currently, this is what we upload:

![image](https://user-images.githubusercontent.com/1271146/87088601-f9971880-c22c-11ea-867f-cccdffa11658.png)

**Comment by gep13** [comment]
If there is one, the dupfinder report is being uploaded as well:

![image](https://user-images.githubusercontent.com/1271146/87088688-1fbcb880-c22d-11ea-9f94-1c49dac053e0.png)

**Comment by AdmiringWorm** [comment]
Looks like the code is missing the files for the coverage report generated by `OpenCover`, as well as test reports from MSBuild projects (don't remember if .NET Core projects generate test results).
But other than that I can't think of any, there could perhaps be some log files that could be useful, but can't think of any right now.

**Comment by gep13** [comment]
@AdmiringWorm apologies, didn't mean to have this one be closed.  Think that there are still some artifacts that we should publish.

**Comment by gep13** [comment]
I have just had a look, and with the exception of the binlog, which we shouldn't ever publish, I think we have everything that we need for now:

![image](https://user-images.githubusercontent.com/1271146/89338420-7682aa00-d694-11ea-8414-dd3a0b29e266.png)

If we need additional artifacts, we can add them as we go.
