### ISSUE TITLE
Build.cake

### ISSUE THREAD

**Issue by wwwlicious** [cake-contrib/Cake.Recipe#66]
Just a couple of observations really on potential usage of incubator addin extensions in `build.cake`, hope you don't mind!

We have a .GetProjects() extension on the solution parser result that filters out solutionfolders so @

https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/build.cake#L157

you could use `ParseSolution(BuildParameters.SolutionFilePath).GetProjects())`

there are also extension methods for checking the project output type so @
https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/build.cake#L182 you could use 

`if(!parsedProject.IsLibrary()) { ... }`

For getting project outputs for nuget packaging or passing to test runner args, we normally use a combination of 

`GetOutputAssemblies(solutionOrProjectFilePath)` and `GetMatchingFiles(outputAssemblyFilePaths)` 

but we don't usually run tests from a diff directory than the project config output path so prob doesn't match your use-case.

**Comment by gep13** [comment]
>@wwwlicious said...
hope you don't mind!

Not at all, always happy to have another set of eyes on this.  Those sound like some very useful optimisations.  I will take a look at some point, unless you felt like doing a PR?

**Comment by wwwlicious** [comment]
lol I considered it but trying to prioritise on some of my own projects right now ;)

Is there any discussion/movement around intellisense in cake scripts as this would likely aid the discoverability for a lot of addin features?

**Comment by gep13** [comment]
>@wwwlicious said...
Is there any discussion/movement around intellisense in cake scripts as this would likely aid the discoverability for a lot of addin features?

There has been lots of discussions around it yes, and I believe that there was a spike to see how it could be done, but nothing more has come of it yet.  We have a meeting to discuss prioritization of tasks in Cake next week, so we might know more about it all then.

>@wwwlicious said...
lol I considered it but trying to prioritise on some of my own projects right now ;)

Not a problem at all, totally understand 😄
