### ISSUE TITLE
Allow tagging of release and hotfix branches to also trigger deployments

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#67]
This will allow for pre-release packages to be published to NuGet and Chocolatey, etc.

**Comment by gep13** [comment]
@pascalberger if/when you have a need, can you take this for a spin?  You should now be able to publish to NuGet/Chocolatey etc, when you have a tagged build on a release/hotfix branch.

**Comment by pascalberger** [comment]
👍 Will test it with the next beta release of Cake.Prca

**Comment by gep13** [comment]
>@pascalberger said...
Will test it with the next beta release of Cake.Prca

Nice one!
