### ISSUE TITLE
Add suport for VS test

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Recipe#7]
~~VS test can be used instead of MS test and an added benefit is that VS test can be used with OpenCover while MS test cannot~~.
MS test in your testing.cake does not work with OpenCover (there's a TODO comment). When I add VS test, I will make sure it works with OpenCover.

Edited to more clearly reflect what I was trying to say

**Comment by gep13** [comment]
@Jericho in principal, I have no objection to this getting added in.  However, to the best of my knowledge, OpenCover is perfectly happy dealing with trx result files which are generated from MSTest.

**Comment by Jericho** [comment]
I was simply trying to point out that MS test in your testing.cake does not work with OpenCover and when I add VS test to your testing.cake I will ensure that it works with OpenCover.

**Comment by gep13** [comment]
@Jericho ah, I see. Gotcha! Yip, that makes sense. I need to go back and add OpenCover to MSTest, it just isn't something I personally use very often, that's why it hasn't been completed yet.
