### ISSUE TITLE
setting GITHUB_TOKEN locally possibly breaks access to GitHub via gh-cli 

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#700]
If `GITHUB_TOKEN` environment-variable is set (as documented in https://cake-contrib.github.io/Cake.Recipe/docs/fundamentals/environment-variables#GITHUB_TOKEN) GitHub cli will detect that and use the token.

This could be a problem when the `GITHUB_TOKEN` is special for one repository while at the same time one tries to access another repository using `gh`.

simple test:
```ps
❯ $env:GITHUB_TOKEN="foo"
❯ gh auth login
? What account do you want to log into? GitHub.com
- Logging into github.com
read-only token in GITHUB_TOKEN cannot be modified
```

So, probably we should use a variable name other than `GITHUB_TOKEN`.

**Comment by AdmiringWorm** [comment]
ah, so this is what you were talking about on the stream.
Now I follow what the issue is.

**Comment by nils-a** [comment]
@gep13 @AdmiringWorm What do you think would be a good replacement?

I was thinking `GH_TOKEN`, `GH_APIKEY` ? 
We could also fall back to `GITHUB_TOKEN` to be backwards compatible. (This would also be interesting/beneficial as `GITHUB_TOKEN` seems to be somewhat official, when using `gh` - so it's quite possible it's set in some places.)

**Comment by gep13** [comment]
@nils-a this one keeps biting me recently, so I am up for getting this fixed sooner rather than later 😄 

Personally, I have been using `GH_TOKEN` in place of `GITHUB_TOKEN`.  If we can do this in a none breaking way, that would be great, otherwise, we can ship a 3.0.0 release.

**Comment by nils-a** [comment]
@gep13 seems `GH_TOKEN` would be a bad choice: https://github.com/cli/cli/commit/a79a0bbfd746566de191cf28cf542ada25c9ef26#diff-463f5a75dbc2dbae5aa080c1450ee05f525eb4f3b1fc16f293b6d2fce431eb76
:confused:

**Comment by gep13** [comment]
Dang it!

We could always be more explicit and call it `GITHUB_PERSONAL_ACCESS_TOKEN` or `GITHUB_PAT`?

**Comment by nils-a** [comment]
I like `GITHUB_PAT`

**Comment by gep13** [comment]
@nils-a am I correct in saying that the way that you have implemented this, that this is no longer a breaking change?

If the GITHUB_PAT variable isn't set, which most folks won't have, it will fall back to the previous values, correct?

**Comment by nils-a** [comment]
Well, yes-and-no. The order is `GITHUB_PAT` (our new value), if that is empty `GH_TOKEN` and if that is empty `GITHUB_TOKEN`. 
(I've chosen that order, because it corresponds to the order used in gh-cli).

So 99.9% I'd say it's backwards compatible. However if someone had a `GH_TOKEN` for gh-cli and a different `GITHUB_TOKEN` for Cake.Recipe, then for this case we would - after this change - use the `GH_TOKEN` not the `GITHUB_TOKEN`.
Having said that - I personally would probably declare this change non-breaking 😉

**Comment by gep13** [comment]
Hmmm, I am inclined to mark it as a non-breaking change as well.

**Comment by AdmiringWorm** [comment]
I would say it sounds like it is non-breaking as well.
While it can be considered to be breaking based on the `gh-cli` itself, it is not in terms of `Cake.Recipe` since it eventually falls back on `GITHUB_TOKEN` if the other two do not exist.

But that is just my opinion.
