### ISSUE TITLE
Builds are failing on GitHub due to usage of set-env

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#724]
The error is 
```
The `set-env` command is disabled. Please upgrade to using Environment Files or opt into unsecure command execution by setting the `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable to `true`. For more information see: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
```

One example for a failing build is: https://github.com/cake-contrib/cake.asciidoctorj/actions/runs/367527911

The solution would be to update to [GitVersion 5.5.0](https://github.com/GitTools/GitVersion/releases/tag/5.5.0) (though 5.5.1 would be better, because it fixes https://github.com/GitTools/GitVersion/pull/2450)

Seemingly we could also work around that by setting `ACTIONS_ALLOW_UNSECURE_COMMANDS` environment variable, though I have not tested that.

**Comment by nils-a** [comment]
Confirmed: Setting `ACTIONS_ALLOW_UNSECURE_COMMANDS` also works.
(see https://github.com/cake-contrib/cake.asciidoctorj/pull/49)

**Comment by gep13** [comment]
@nils-a this is being addressed by an existing PR, but thanks for raising this!
