### ISSUE TITLE
Releasing a new version will not post to twitter on GH-Actions

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#738]
I experienced this error (no twitter message sent, when it *should* be) when [releasing `test-rider` using `Cake.IntelliJ.Recipe`](https://github.com/nils-a/test-rider/runs/1631914646?check_suite_focus=true) (see the ubuntu run, there). I started analyzing  for https://github.com/nils-a/Cake.IntelliJ.Recipe/issues/14.

While analyzing, I came across this in the logs:

```
BranchType: Unknown
```

which explains that the post was not made: `build.cake` sends all messages only for `BranchType.Master` (or `BranchType.Release` or `BranchType.HotFix` when `BuildParameters.ShouldNotifyBetaReleases` is set.)

I compared to [Cake.7zip](https://github.com/cake-contrib/Cake.7zip/runs/1222831699?check_suite_focus=true) and [Cake.asciidoctorj](https://github.com/cake-contrib/cake.asciidoctorj/runs/1582904745?check_suite_focus=true) (both have appVeyor as `preferredBuildProviderType` so I never noticed the problem there...) and every build in GH-Actions that is based on a tag, has `BranchType` set to `Unknown`. ("Every" being based on my sample of three.)

Compared to builds on appVeyor this seems to be the error. Builds on appVeyor that are tag-builds have `BranchType` set corresponding to the branch being tagged. I.e. `Master` for the above mentioned cases of [Cake.7zip](https://ci.appveyor.com/project/cakecontrib/cake-7zip/builds/35627100) and [Cake.asciiddoctorj](https://ci.appveyor.com/project/cakecontrib/cake-asciidoctorj/builds/36924024).

I think the culprit is `context.BuildSystem().GitHubActions.Environment.Workflow.Ref` in `github-actions.cake`: For tagged builds on GH-Actions, `ref` is the tag-name. I.e. `refs/tags/0.2.0` for the release build of `test-rider`.

**Comment by nils-a** [comment]
@AdmiringWorm you do have projects with `preferredBuildProviderType: BuildProviderType.GitHubActions`, right? Have you had this problem?

**Comment by gep13** [comment]
@nils-a I personally haven't moved any project to GitHub fully yet, as there was an ongoing issue with GitVersion which was making it not work properly on tagged builds.  I think this has now been addressed though, but not started the process of moving over yet.

**Comment by nils-a** [comment]
I see. (Probably should continue my tests on appVeyor, then 😄 )

Nonetheless this issue would make moving difficult, too.

**Comment by gep13** [comment]
Sounds like a potential candidate for investigating on stream...  This is something that I would like to get working, as a lot of work was done to get the support for different build providers.

**Comment by nils-a** [comment]
Good idea. I am certain I fount the "error" (not sure about a fix, though). If you compare in `github-actons.cake` the lines 5-6 with 31-33 (esp. 5 with 31) this will never work correctly.

Not sure about a fix though. According to the docs I fear the "original" branch is not provided to us.
So... a fix could be calling `git`. Something like `git branch --contains tags/0.2.0` should work.

**Comment by AdmiringWorm** [comment]
> Good idea. I am certain I found the "error" (not sure about a fix, though). If you compare in github-actons.cake the lines 5-6 with 31-33 (esp. 5 with 31) this will never work correctly.

Different use case for both of them, 1 is for the tags the other for branch names. They aren't meant to be equal.

The problem is github actions itself, when it checks out a tag it checks it out in a detached state, without having a reference to the actual branch name of the commit (same thing happens on appveyor if you create a tag manually and push it, instead of creating it through the github UI).

I have seen this happen, on my own projects, but haven't found a solution other than using gha for most commits, but appveyor on a tagged commit.

The problem with it not sending the twitter message is due to the above and to the criteria here: https://github.com/cake-contrib/Cake.Recipe/blob/f7b0621645e8c8e9e709ea6e12d7957e781675c3/Cake.Recipe/Content/build.cake#L31-L33

Since it isn't possible to detect the git branch (at least I haven't found out how) on tagged releases, this evaluates to false every time and sending messages is disabled.

**Comment by nils-a** [comment]
@AdmiringWorm agreed. 

However:

Lines 5/6 says:
```
var tempName = context.BuildSystem().GitHubActions.Environment.Workflow.Ref;
if (!string.IsNullOrEmpty(tempName) && tempName.IndexOf("tags/") >= 0)
``` 

So we're using `context.BuildSystem().GitHubActions.Environment.Workflow.Ref` and if it contains `tags/` it's a tag and the part after the last `/` contains the tag-name.

line 31 uses the exact same thing (environment variable) i.e. `context.BuildSystem().GitHubActions.Environment.Workflow.Ref` and assumes the part after the last `/` is the branch name.

Both can not be true at the same time.

Or am I missing something?

**Comment by AdmiringWorm** [comment]
> Both can not be true at the same time.
> Or am I missing something?

Nope, you are correct, however the Ref will always be a tag for tagged builds (and BaseRef will be empty).
The part that checks the branch name will only be valid for branch builds, for tagged builds it will be more or less the same as the tag check (although you don't see that in the log, everything not matching master, develop, hotfix, release etc will always be unknown in the log).

This is unfortunately a limitation on the GitHub action though.

**Comment by gep13** [comment]
We tackled this on the stream tonight, and we have a working solution that correctly identifies that branch name, based on using `git branch -r --contains {{ github.ref }}`

In order for this to work, the following is required in the workflow file:

```
      - name: Fetch all history for all tags and branches
        run: git fetch --prune --unshallow
```

**Comment by nils-a** [comment]
@gep13 @AdmiringWorm I *think* we fixed this only for non-windows systems (And I think we checked only ubuntu yesterday).

If you check the ubuntu run from yesterday at https://github.com/gep13/CakeRecipeGHA/runs/1646503805?check_suite_focus=true#step:5:536 it reads:
```
Using GitHub Action Provider...
Resolved tool to path /usr/bin/git
Executing: /usr/bin/git branch -r --contains refs/tags/0.7.0
  origin/main
Printing Build Parameters...
```

compare that with the windows run at https://github.com/gep13/CakeRecipeGHA/runs/1646503796?check_suite_focus=true#step:5:750. It reads:

```
Using GitHub Action Provider...
Could not resolve path for tool "git" using these directories: [....]
Could not resolve path for tool "git" using these directories: [....]
Printing Build Parameters...
``` 

and this run also results in `BranchType: Unknown`

**Comment by nils-a** [comment]
I have done some quick checks and it seems `context.Tools.Resolve("git")` has never been working for me anyway.

Building Cake.7zip (or any other Cake.Recipe enabled project) always starts like this:
![image](https://user-images.githubusercontent.com/349188/103651404-d2ae6a80-4f61-11eb-9b35-15cf2dd8ddba.png)
