### ISSUE TITLE
Replace Gitter with GitHub Discussions

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#750]
The Discussion platform for Cake-Contrib has been moved from Gitter to GitHub Discussion (see cake-build/website#1470). 
Please check this repo for references to Gitte and replace them accordingly.

Search suggests that references could be in

 - README.md
 - docs/input/_Bottom.cshtml

**Comment by gep13** [comment]
@nils-a thanks for the nudge on this!
