### ISSUE TITLE
Unable to publish when running on Azure Pipelines

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#768]
When running a tag build on Azure Pipelines, the IsTagged property is false, when it should be true.

Looking that the code, it is using the SourceBranchName, rather than SourceBranch.  As per the docs here:

https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml#build-variables-devops-services

The latter will only include something like `0.3.0`, where as the logic for IsTagged needs the full branch name, which would be `refs/tags/0.3.0`

**Comment by gep13** [comment]
Looks like there is still an underlying issue here.

When running on a tagged build, it is necessary to do some additional work, otherwise the BranchType is unknown, which causes sending out tweets/gitter messages etc to not work.

**Comment by AdmiringWorm** [comment]
@gep13 just a thought. Should maybe the twitter and gitter code just consider if the build is tagged, and pretty much ignore everything else?

**Comment by gep13** [comment]
@AdmiringWorm I did consider that, but I think that might be a change for another day.

Having the actual branch name available is still a good thing to have, and once we have it working reliably, I think we can look to refactor is it no longer becomes a requirement for certain actions.
