### ISSUE TITLE
Don't notify Gitter/Twitter for beta releases

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#79]
Currently if a beta release is tagged and published a notification will be send to Gitter. I'm not sure if this makes sense in all cases.

**Comment by gep13** [comment]
@pascalberger  What about Twitter?  Does it fall under the same thing?

https://twitter.com/cakecontrib/status/847152981841776640

**Comment by pascalberger** [comment]
@gep13 IMHO yes. Or even more since it propably is more public than a Gitter room
