### ISSUE TITLE
Nupkg uploaded to wrong GitHub release

### ISSUE THREAD

**Issue by pascalberger** [cake-contrib/Cake.Recipe#80]
If a beta release is created for a release branch (eg. 0.3.0-beta.1) while already a draft release exists for the final release (eg. 0.3.0), the .nupkg artifact will be uploaded to the final release instead of the beta release.

**Comment by AdmiringWorm** [comment]
This may look like it's because the milestone is blindly set to the version (MajorMinorPatch).
Perhaps it would be better to set it to the `assertedVersion.SemVer` instead?

/cc @gep13

**Comment by gep13** [comment]
@AdmiringWorm yes, I think you could be right.

My usage of GitVersion, and Cake.Recipe, has really only been with releases coming from the master branch, therefore, it is not a surprise that there could be some issues with trying to push out releases from other tags.

**Comment by gep13** [comment]
@AdmiringWorm so looking at the code, this is exactly the issue 😢
