### ISSUE TITLE
Changing title away from the repository name, breaks edit badge in wyam and appveyor

### ISSUE THREAD

**Issue by nils-a** [cake-contrib/Cake.Recipe#816]
This is more a theory than a real bug, because I did not really test this (yet). 
However, if I set e.g.

```
BuildParameters.SetParameters(
  // ...
  title: "Cake for Rider",
  repositoryName: "Cake-Rider"
);
```

instead of the "usual"
```suggestion
BuildParameters.SetParameters(
  // ...
  title: "Cake-Rider"
);
```

In `parameters.cake`

* [`AppVeyorProjectSlug`](https://github.com/cake-contrib/Cake.Recipe/blob/8a9f629b287a4361fb159dccacb4b88c29440c6f/Cake.Recipe/Content/parameters.cake#L445) is initialized with a default of `Title.Replace(".", "-").ToLower()` 
* [`WebBaseEditUrl`](https://github.com/cake-contrib/Cake.Recipe/blob/8a9f629b287a4361fb159dccacb4b88c29440c6f/Cake.Recipe/Content/parameters.cake#L463) is initialized with a default of `string.Format("https://github.com/{0}/{1}/tree/{2}/docs/input/", repositoryOwner, title, developBranchName)`

Both references to [Tt]itle should IMHO be set to `RepositoryName`.

**Comment by AdmiringWorm** [comment]
I do believe you are correct that both of those places should use the `RepositoryName` instead of the specified title, and would classify it as a bug as well.

I guess it hasn't been discovered/mentioned before due to (I assume) most people have the title and repository name as the same value.
