### ISSUE TITLE
Extend ToolSettings for additional DupFinder settings

### ISSUE THREAD

**Issue by kcamp** [cake-contrib/Cake.Recipe#82]
It would be useful to support some of the additional properties supported by `DupFinderSettings`, specifically the ability to customize the `ThrowExceptionOnFindingDuplicates` and `DiscardCost` behavior.

I have made an initial pass at adding what I need more immediately and will create a PR shortly.

**Comment by gep13** [comment]
@kcamp great idea!  Thanks for doing this!
