### ISSUE TITLE
Support ability to only load the tools that are actually required

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#84]
Since some Tasks are never ran, based on the conventions of the script, it doesn't make sense to resolve the tools if they aren't required.

**Comment by gep13** [comment]
@pascalberger I have just committed a fairly fundamental change, that might break a few things 😄 Just wanted to give you a heads up in case you run into anything.  I have tested it on a few projects here, and seems to work fine though.

Let me know if you notice anything.

**Comment by pascalberger** [comment]
@gep13 Oh nice! Had this also on my todo list for our inhouse scripts :)

**Comment by gep13** [comment]
>@pascalberger said...
Oh nice! Had this also on my todo list for our inhouse scripts :)

This is an implementation of an idea that @devlead came up with.  It is some evil magic that he is weaving, but seems to work really well.
