### ISSUE TITLE
Build doesn't work with new csproj format

### ISSUE THREAD

**Issue by erikvanbrakel** [cake-contrib/Cake.Recipe#87]
I'm trying to compile two versions (net452 and net-standard1.6) of Cake.Terraform. However, when trying to build, it can't seem to parse the project files. Seems logical, as the new csproj file format is quite different.

Build logs can be found here: https://ci.appveyor.com/project/erikvanbrakel/cake-terraform
Current version is here: https://github.com/erikvanbrakel/Cake.Terraform/tree/multi-targeting

Any thoughts on how to work around this? I'm more than willing to help out on this, but don't really know where to start.

**Comment by gep13** [comment]
@erikvanbrakel simply put...

Cake.Recipe doesn't work currently with the new format.  It is on the roadmap, but I suspect that lots of things will break until this https://github.com/cake-contrib/Cake.Recipe/issues/10 is implemented.

**Comment by gep13** [comment]
@erikvanbrakel would you be in a position to try this out using the latest Cake.Recipe available on the MyGet feed?

You should be able to use:

`#load nuget:https://www.myget.org/F/cake-contrib/api/v2?package=Cake.Recipe&prerelease`

and instead of calling `Build.Run()` call `Build.RunDotNetCore()`.

Let us know how you get on.

**Comment by erikvanbrakel** [comment]
I'll give it a shot, will let you know!

**Comment by erikvanbrakel** [comment]
https://ci.appveyor.com/project/erikvanbrakel/cake-terraform/build/1.0.74 Seems to work now! I had to fix a few things on my end (most notably the nuspec file) to be able to build a multi-targeting nuget package.

**Comment by gep13** [comment]
@erikvanbrakel sweet! Glad to hear that it is working.

Am I ok to close this issue now?

**Comment by erikvanbrakel** [comment]
Sure. If it turns out it's not working after all I'll just ask you to re-open ;-)
