### ISSUE TITLE
GitReleaseManager - pre-release flag

### ISSUE THREAD

**Issue by gep13** [cake-contrib/Cake.Recipe#89]
Currently, we have this:

https://github.com/cake-contrib/Cake.Recipe/blob/develop/Cake.Recipe/Content/gitreleasemanager.cake#L12

Where the pre-release flag is set to true by default.  However, based on this discussion:

https://github.com/cake-contrib/Home/issues/5

I no longer believe that this is the case.  If we are creating a pre-release version, i.e. 0.1.0-beta0001 or 0.1.0-rc0001, then I think the pre-release flag should be set, and otherwise, if we are just doing 0.1.0, it shouldn't be set.

I am not clear how/where to make that distinction though.

@pascalberger any thoughts on this?

**Comment by Jericho** [comment]
I vote for simply setting it to false because from now on it will be the setting that's used most regularly. Anyway, the release must be reviewed and published manually which means that this setting can be changed when necessary (in my opinion, this should be very rare in fact).

**Comment by gep13** [comment]
@Jericho yes, I think I tend to agree with this.
