### ISSUE TITLE
Add metadata to package with supported Cake version and TFMs

### ISSUE THREAD

**Issue by Jericho** [cake-contrib/Cake.Recipe#921]
Just like @pascalberger did in Cake.Issues.Recipe ([here](https://github.com/cake-contrib/Cake.Issues.Recipe/pull/297)), we should add cake-version.yml to Cake.Recipe. This would allow AddinDiscoverer to **reliably** detect the supported version of Cake.

The current AddinDiscoverer logic is to parse the content of `.config/dotnet-tools.json` which works fine as long as the content of this file matches the content of the nuget package. However this logic breaks down when @gep13 starts working on his next release that will eventually target the next version of Cake. As soon as this file is modified and committed to the git repo, AddinDiscoverer "thinks" that Cake..Recipe has been upgraded when in fact it hasn't. The consequence is that AddinDiscoverer no longer updates the "Support Cake x.y.z" issue (such as [this one](https://github.com/cake-contrib/Cake.Recipe/issues/872)).

**Comment by nils-a** [comment]
@Jericho Should the yml only include `TargetCakeVersion` or should it also include `TargetFrameworks`?

While there is a .NET project here, that defines a `TargetFramework` (`netstandard2.0`) the dll is not shipped, so there is really nothing here that has a `TargetFramework`.  

Can I omit `TargetFrameworks`, or leave it empty?

**Comment by Jericho** [comment]
@nils-a as far as Cake.AddinDiscoverer is concerned, only `TargetCakeVersion` is useful. Feel free to omit TargetFrameworks.
